name: final_exam
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  badges: ^2.0.1
  cupertino_icons: ^1.0.2
  # easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_osm_plugin: ^0.39.1
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^5.0.0
  # sqflite: ^2.1.0+1
  geolocator: ^9.0.2
  qr_flutter: ^4.0.0
  flutter_google_location_picker: ^0.0.3
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

